name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:

  release-please:
    runs-on: ubuntu-latest
    outputs:
      hello-react--tag_name: ${{ steps.release.outputs.hello-react--tag_name}}
      hello-react--release_created: ${{ steps.release.outputs.hello-react--release_created}}
      hello-rust--tag_name: ${{ steps.release.outputs.hello-rust--tag_name}}
      hello-rust--release_created: ${{ steps.release.outputs.hello-rust--release_created}}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          
      - name: Print release outputs for debugging
        continue-on-error: true
        run: |
          echo "Release outputs:"
          echo "${{ toJson(steps.release.outputs) }}"
          echo "${{ steps.release.outputs.hello-react--tag_name}}"
          echo "${{ steps.release.outputs.hello-react--release_created}}"
          echo "${{ steps.release.outputs.hello-rust--tag_name}}"
          echo "${{ steps.release.outputs.hello-rust--release_created}}"
          
  release-react:
    if: ${{needs.release-please.outputs.hello-react--release_created}}
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - uses: actions/checkout@v4
      - run: echo "xyz" > react-build.zip
      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ needs.release-please.outputs.hello-react--tag_name }} react-build.zip

  release-rust:
    if: ${{needs.release-please.outputs.hello-rust--release_created}}
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - uses: actions/checkout@v4
      - run: echo "xyz" > rust-build.zip
      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ needs.release-please.outputs.hello-rust--tag_name }} rust-build.zip
